from enum import Enum
from typing import List, Dict, Any
from pydantic import BaseModel, Field


class DocumentType(str, Enum):
    STANDARD = "standard"
    LEGAL = "legal"
    TECHNICAL = "technical"


class ChatRequest(BaseModel):
    doc_ids: List[str] = Field(
        ..., description="List of unique document identifiers to retrieve context from."
    )
    message: str = Field(..., description="The user query or message.")


class UploadResponse(BaseModel):
    message: str = Field(..., description="Status message of the upload processing.")
    doc_id: str = Field(
        ..., description="The unique document identifier autogenerated for the PDF."
    )
    filename: str = Field(..., description="The name of the uploaded PDF file.")
    version: int = Field(
        ..., description="The version number assigned to this document upload."
    )


class DocumentMetadata(BaseModel):
    id: str = Field(..., description="The unique generated document ID.")
    filename: str = Field(..., description="The name of the uploaded file.")
    version: int = Field(..., description="The version number of the document.")
    status: str = Field(
        ..., description="The status of the document: 'active' or 'archived'."
    )
    uploaded_at: str = Field(
        ..., description="ISO timestamp of when the file was processed."
    )


class GenericMessageResponse(BaseModel):
    message: str = Field(
        ..., description="Detailed status message of the completed action."
    )


class ChunkItem(BaseModel):
    id: str = Field(..., description="The unique chunk ID.")
    text: str = Field(..., description="The chunk text segment.")
    metadata: Dict[str, Any] = Field(
        ..., description="Metadata dict associated with the chunk."
    )


class ChunkListResponse(BaseModel):
    chunks: List[ChunkItem] = Field(
        ..., description="List of all chunk records matching the document ID."
    )
