from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    doc_id: str = Field(
        ..., description="The unique document identifier to retrieve context from."
    )
    message: str = Field(..., description="The user query or message.")


class UploadResponse(BaseModel):
    message: str = Field(..., description="Status message of the upload processing.")
    doc_id: str = Field(
        ..., description="The unique document identifier autogenerated for the PDF."
    )
    filename: str = Field(..., description="The name of the uploaded PDF file.")
    version: int = Field(
        ..., description="The version number assigned to this document upload."
    )


class DocumentMetadata(BaseModel):
    id: str = Field(..., description="The unique generated document ID.")
    filename: str = Field(..., description="The name of the uploaded file.")
    version: int = Field(..., description="The version number of the document.")
    status: str = Field(
        ..., description="The status of the document: 'active' or 'archived'."
    )
    uploaded_at: str = Field(
        ..., description="ISO timestamp of when the file was processed."
    )
